name = "tool::tailwind"
version = "1.8.10"
description = "Build tool for tailwind CSS"
type = "hook"
keywords = ["Tailwind", "CSS"]

[library.tailwind]
version = "1.8.10"
website = "https://tailwindcss.com"
repository = "https://github.com/tailwindlabs/tailwindcss"

[[hooks.run]]
path = "node"
args = ["build.js"]
files = ["tailwind.config.js", "assets/css/style.css"]
watch = true

