name = "tool::tailwind"
version = "1.4.6"
description = "Build tool for tailwind CSS"
type = "hook"
keywords = ["Tailwind", "CSS"]

[hooks.tailwind]
path = "node"
args = ["build.js"]
files = ["tailwind.config.js", "assets/css/style.css"]
watch = true

[library.tailwind]
version = "1.4.6"
website = "https://tailwindcss.com"
repository = "https://github.com/tailwindlabs/tailwindcss"
