name = "std::link"
version = "1.0.4"
description = "Partials for creating absolute links"
repository = "https://github.com/uwe-app/plugins"
type = "library"
keywords = ["Layout", "Partial"]
license = ["MIT", "Apache-2.0"]

[features]
default = []
