name = "css::new"
description = "Stylesheet for the new.css classless framework"
version = "1.1.3"
keywords = ["Style", "Classless"]
type = "style"

[library.newcss]
version = "1.1.3"
website = "https://newcss.net/"
repository = "https://github.com/xz/new.css"
commit = "45cc63d759c3960095a6d8cf97f8663c6561efcc"
