name = "std::alert"
version = "1.0.0"
description = "Render info, tips, warning alerts etc"
repository = "https://github.com/uwe-app/plugins"
type = "library"
keywords = ["Layout", "Partial"]
license = ["MIT", "Apache-2.0"]
