name = "std::core"
version = "5.0.2"
description = "Standard layout, partials and stylesheet"
repository = "https://github.com/uwe-app/plugins"
type = "library"
keywords = ["Layout", "Partial"]
license = ["MIT", "Apache-2.0"]
