name = "std::core"
version = "1.0.1"
description = "Standard partials and layouts"
type = "partial"
keywords = ["Layout", "Partial"]

[handlebars.layouts.main]
file = "handlebars/layouts/layout.hbs"
description  = "Default page layout"

[handlebars.partials.header]
file = "handlebars/partials/header.hbs"
description = "Placeholder for a page header"

[handlebars.partials.footer]
file = "handlebars/partials/footer.hbs"
description = "Placeholder for a page footer"

[handlebars.partials.head]
file = "handlebars/partials/head.hbs"
description = "Sets the content for a standard page head"

[handlebars.partials.charset]
file = "handlebars/partials/charset.hbs"
schema = "schema/charset.json"
description = "Adds the utf-8 charset to a page"

[handlebars.partials.title]
file = "handlebars/partials/title.hbs"
schema = "schema/title.json"
description = "Sets the page title"

[handlebars.partials.viewport]
file = "handlebars/partials/viewport.hbs"
description = "Sets the page viewport"

[handlebars.partials.edge]
file = "handlebars/partials/edge.hbs"
description = "Sets Edge compatibility"

[handlebars.partials.description]
file = "handlebars/partials/description.hbs"
schema = "schema/description.json"
description = "Sets the page description"

[handlebars.partials.keywords]
file = "handlebars/partials/keywords.hbs"
schema = "schema/keywords.json"
description = "Sets the page keywords"

[handlebars.partials.canonical]
file = "handlebars/partials/canonical.hbs"
schema = "schema/canonical.json"
description = "Sets the page canonical URL"

[handlebars.partials.noindex]
file = "handlebars/partials/noindex.hbs"
schema = "schema/noindex.json"
description = "Sets the meta noindex for search robots"
