name = "font::open-sans"
version = "1.0.0"
description = "Open sans typeface"
repository = "https://github.com/uwe-app/plugins"
keywords = ["Font", "Sans"]
type = "library"
license = ["MIT", "Apache-2.0"]

[library.open-sans]
version = "2.0.10"
website = "https://fonts.adobe.com/fonts/open-sans"
repository = "https://github.com/googlefonts/opensans"
license = "Apache-2.0"
