name = "font::inter"
description = "Inter UI"
version = "3.15.0"
keywords = ["Font", "UI"]
type = "library"
license = ["MIT", "Apache-2.0"]

[features]
default = ["font::inter::regular"]

[library.inter]
version = "3.15.0"
website = "https://rsms.me/inter/"
repository = "https://github.com/rsms/inter"
license = "OFL-1.1"
