name = "font::inter"
description = "Inter UI"
version = "3.15.0"
keywords = ["Font", "UI"]
type = "font"
license = "SIL"

[library.inter]
version = "3.15.0"
website = "https://rsms.me/inter/"
repository = "https://github.com/rsms/inter"

