name = "font::awesome"
description = "Font awesome icons"
version = "5.14.0"
keywords = ["Font", "Icons"]
type = "font"
license = "SIL"

[library.font-awesome]
version = "5.14.0"
website = "https://fontawesome.com"
repository = "https://github.com/FortAwesome/Font-Awesome"

