name = "font::awesome"
description = "Font awesome icons"
version = "5.14.0"
keywords = ["Font", "Icons"]
type = "font"
license = "SIL"

styles = ["fonts.css"]
assets = [
  "fa-brands-400.eot",
  "fa-brands-400.svg",
  "fa-brands-400.ttf",
  "fa-brands-400.woff",
  "fa-brands-400.woff2",
  "fa-regular-400.eot",
  "fa-regular-400.svg",
  "fa-regular-400.ttf",
  "fa-regular-400.woff",
  "fa-regular-400.woff2",
  "fa-solid-900.eot",
  "fa-solid-900.svg",
  "fa-solid-900.ttf",
  "fa-solid-900.woff",
  "fa-solid-900.woff2"
]

[[library]]
version = "5.14.0"
website = "https://fontawesome.com"
repository = "https://github.com/FortAwesome/Font-Awesome"

