name = "std::sidebar"
version = "2.1.0"
description = "Standard sidebar"
repository = "https://github.com/uwe-app/plugins"
type = "library"
keywords = ["Layout", "Aside", "Navigation"]
license = ["MIT", "Apache-2.0"]
